# needed for python unit testings
# https://docs.python.org/3/library/unittest.html
import unittest

# required for type hinting
# https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html
from typing import List, Dict, Set, Optional

class Solution:
    '''
    Given three positive integers num1, num2, and num3.

    The key of num1, num2, and num3 is defined as a four-digit number such that:
    * Initially, if any number has less than four digits, it is padded with
      leading zeros.
    * The ith digit (1 <= i <= 4) of the key is generated by taking the smallest
      digit among the ith digits of num1, num2, and num3.

    Return the key of the three numbers without leading zeros (if any).
    '''
    def generateKey(self, num1: int, num2: int, num3: int) -> int:
        return int("".join(min(i,j,k) for i,j,k in zip(f"{num1:04d}",f"{num2:04d}",f"{num3:04d}")))

class UnitTesting(unittest.TestCase):
    def test_one(self):
        s = Solution()
        i = 1,10,1000
        o = 0
        self.assertEqual(s.generateKey(*i), o)

    def test_two(self):
        s = Solution()
        i = 987, 879, 798
        o = 777
        self.assertEqual(s.generateKey(*i), o)

    def test_three(self):
        s = Solution()
        i = 1, 2, 3
        o = 1
        self.assertEqual(s.generateKey(*i), o)

if __name__ == '__main__':
    unittest.main(verbosity=2)