# needed for python unit testings
# https://docs.python.org/3/library/unittest.html
import unittest

# required for type hinting
# https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html
from typing import List, Dict, Set, Optional

class Solution:
    '''
    Given two strings, str1 and str2 of lengths n and m, respectively.

    A string word of length n + m - 1 is defined to be generated by str1 and
    str2 if it satisfies the following conditions for each index
    0 <= i <= n - 1.
    * If str1[i] == 'T', the substring of word with size m starting at index i
      is equal to str2 (word[i..(i+m-1)] == str2)
    * If str2[i] == 'F', the substring of word with size m starting at index i
      is not equal to str2 (word[i..(i+m-1)] != str2).

    Return the lexicographically smallest possible string that can be generated
    by str1 and str2. If no string can be generated, return an empty string "".
    '''
    # fails because all the applications need to be made at once then tested
    def generateString_fails(self, str1: str, str2: str) -> str:
        n,m = len(str1), len(str2)
        k = n + m - 1
        answer = [""] * k
        for i,j in enumerate(str1):
            if j == 'T':
                for x,y in enumerate(str2):
                    if answer[i+x] != "" and answer[i+x] != y:
                        return ""
                    answer[i+x] = y
            else:
                for x,y in enumerate(str2):
                    if answer[i+x] == y:
                        return ""
        return "".join(a if a != '' else 'a' for a in answer)

    # fails because there are cases where answer is possible but the answer
    # at an index should be 'b' instead of 'a'
    def generateString_closer(self, str1: str, str2: str) -> str:
        n,m = len(str1), len(str2)
        k = n + m - 1
        answer = [""] * k
        for i,j in enumerate(str1):
            if j == 'T':
                for x,y in enumerate(str2):
                    if answer[i+x] != "" and answer[i+x] != y:
                        return ""
                    answer[i+x] = y
        for i,j in enumerate(str1):
            if j == 'F' and all(answer[i+x] == y for x,y in enumerate(str2)):
                return ""
        # for i in range(k,m-1,-1):
        #     if answer[i] != '':
        #         continue
        #     answer[i] = 'a'
        return "".join(a if a != '' else 'a' for a in answer)

    # edited based on editorial description
    # https://leetcode.com/problems/lexicographically-smallest-generated-string/editorial/?envType=daily-question&envId=2026-03-31
    def generateString(self, str1: str, str2: str) -> str:
        n,m = len(str1), len(str2)
        k = n + m - 1
        answer = [""] * k
        fixed = [False] * k
        for i,j in enumerate(str1):
            if j == 'T':
                for x,y in enumerate(str2):
                    if answer[i+x] != "" and answer[i+x] != y:
                        return ""
                    answer[i+x] = y
                    fixed[i+x] = True
        for i in range(k):
            if answer[i] == '':
                answer[i] = 'a'
        for i,j in enumerate(str1):
            if j == 'F':
                if all(answer[i+x] == y for x,y in enumerate(str2)):
                    for k in range(i+m-1,i-1,-1):
                        if fixed[k] == False:
                            answer[k] = 'b'
                            break
                    else:
                        return ""
        return "".join(answer)

class UnitTesting(unittest.TestCase):
    def test_one(self):
        s = Solution()
        i = "TFTF"
        j = "ab"
        o = "ababa"
        self.assertEqual(s.generateString(i,j), o)

    def test_two(self):
        s = Solution()
        i = "TFTF"
        j = "abc"
        o = ""
        self.assertEqual(s.generateString(i,j), o)

    def test_three(self):
        s = Solution()
        i = "F"
        j = "d"
        o = "a"
        self.assertEqual(s.generateString(i,j), o)

    def test_four(self):
        s = Solution()
        i = "TT"
        j = "aaa"
        o = "aaaa"
        self.assertEqual(s.generateString(i,j), o)

    def test_five(self):
        s = Solution()
        i = "TTFFT"
        j = "fff"
        o = ""
        self.assertEqual(s.generateString(i,j), o)

    def test_six(self):
        s = Solution()
        i = "FTF"
        j = "xww"
        o = "axwwa"
        self.assertEqual(s.generateString(i,j), o)

    def test_seven(self):
        s = Solution()
        i = "FFTFFF"
        j = "a"
        o = "bbabbb"
        self.assertEqual(s.generateString(i,j), o)

    def test_eight(self):
        s = Solution()
        i = "FFTFFF"
        j = "aa"
        o = "abaabab"
        self.assertEqual(s.generateString(i,j), o)

if __name__ == '__main__':
    unittest.main(verbosity=2)